name: Full Stack CI/CD with Render

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    name: Build & Deploy Backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        working-directory: backend
        run: npm install

      - name: Lint backend
        working-directory: backend
        run: npm run lint || echo "No linter configured"

      - name: Run backend tests
        working-directory: backend
        run: npm test || echo "No tests configured"

      - name: Deploy backend to Render
        run: curl -X POST ${{ secrets.RENDER_BACKEND_HOOK }}

  frontend:
    runs-on: ubuntu-latest
    name: Build & Deploy Frontend
    needs: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy frontend to Render
        run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}

  notify:
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    steps:
      - name: Notify Slack (Success)
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"✅ Full-Stack Deployed Successfully to Render!"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack (Failure)
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"❌ Full-Stack Deployment Failed. Check pipeline."}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}
